module.exports = [{
    NAZWA: "I Historyczne centrum Krakowa",
    NUMER_WPISU: "29bis",
    DATA_WPISU: "1978",
    MIEJSCOWOSC: "Kraków",
    N: 50.0558725738616,
    E: 19.9410154597768,
    OPIS: "Historyczne centrum Krakowa, położone nad Wisłą na południu Polski, tworzą trzy zespoły miejskie: średniowieczne miasto lokacyjne Kraków, kompleks Wzgórza Wawelskiego oraz Kazimierz (w tym dzielnica Stradom). To jeden z najwybitniejszych przykładów urbanistyki europejskiej, charakteryzujący się harmonijnym rozwojem i nawarstwieniami elementów reprezentujących wszystkie style architektoniczne od wczesnej fazy romańskiej po modernizm.\n" +
        "O randze miasta, które założono w 1257 roku i było wcześniej stolicą Polski, świadczą zachowane do dziś układ urbanistyczny, liczne świątynie i klasztory, monumentalne budowle użyteczności publicznej, relikty średniowiecznych murów obronnych, a także pałace miejskie i kamienice mieszczańskie projektowane i wykonane przez wysokiej klasy architektów i rzemieślników. O wartości zespołu decyduje niezwykłe nagromadzenie zabytków z różnych epok, zachowanych w oryginalnej postaci, z autentycznym wyposażeniem, które łączą się w jednolity zespół miejski. Dominanta zespołu urbanistycznego – Wzgórze Wawelskie, jest symbolem władzy królewskiej, nekropolią dokumentującą związki dynastyczne i polityczne średniowiecznej i nowożytnej Europy. Średniowieczne miasto Kazimierz, które obejmuje także przedmieście Stradomia (założone w 1335 roku), zostało ukształtowane przez ludność wiary katolickiej i żydowskiej oraz ich kultury i zwyczaje.\n" +
        "Kraków, jedno z największych centrów administracyjno-handlowych Europy Środkowej, był ośrodkiem sztuki i rzemiosła, miejscem, gdzie spotykała się kultura i sztuka Zachodu i Wschodu. Rangę miasta jako ośrodka kulturalnego o europejskim znaczeniu podnosi istnienie jednego z najstarszych uniwersytetów o międzynarodowej renomie – Uniwersytet Jagielloński. Te trzy obszary wspólnie stworzyły spójny kompleks miejski, w którym do dziś zachowane i pielęgnowane jest materialne i niematerialne dziedzictwo.\n",
    ZDJECIE1: require("./images/01. Historyczne centrum Krakowa (wpis 1978)/Krakow (1).jpg"),
    ZDJECIE2: require("./images/01. Historyczne centrum Krakowa (wpis 1978)/Krakow (2).jpg"),
    ZDJECIE3: require("./images/01. Historyczne centrum Krakowa (wpis 1978)/Krakow (3).jpg"),
}, {
    NAZWA: "II Królewskie Kopalnie Soli w Wieliczce i Bochni - kopalnia soli w Bochni",
    NUMER_WPISU: "32ter",
    DATA_WPISU: "1978",
    MIEJSCOWOSC: "Bochnia",
    N: 49.9699238339928,
    E: 20.4212794693282,
    OPIS: "Kopalnia soli w Bochni została uznana za pomnik historii w 2000 roku. Jest ona najstarszym na ziemiach polskich miejscem wydobycia soli kamiennej - najważniejszej w historii rodzimego górnictwa kopaliny, której pokłady odkryto tu w połowie XIII wieku, kilkadziesiąt lat wcześniej niż w pobliskiej Wieliczce. Powstające w tym samym czasie miasto to doskonały przykład średniowiecznego miasta górniczego, którego kształt został całkowicie podporządkowany rozwojowi kopalni. Od końca XIII wieku żupa bocheńska tworzyła wraz z Wieliczką niezwykle prężnie działające przedsiębiorstwo, największe w dawnej Rzeczypospolitej, a drugie w Europie, pod nazwą Krakowskie Żupy Solne. Przez blisko 500 lat przynosiło ono znaczne dochody zasilające skarb królewski, a w okresie swojego największego rozkwitu, przez wzgląd na niebagatelne znaczenie dla gospodarki państwa, zapewniało miastu i górnikom opiekę monarchy. Kopalnia w Bochni jest bezcennym zabytkiem techniki dokumentującym dawne sposoby wydobycia soli. Dzięki prowadzonej od połowy XVIII wieku akcji jej zabezpieczania zarówno stare wyrobiska, jak i unikatowe kaplice kute w solnych skałach zachowane są w bardzo dobrym stanie. Wyczerpanie w XX wieku pokładów soli nie spowodowało zamknięcia kopalni - jej podziemia udostępniane są dziś w celach edukacyjnych i uzdrowiskowych.",
    ZDJECIE1: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Bochnia/Bochnia (1).jpg"),
    ZDJECIE2: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Bochnia/Bochnia (2).jpg"),
    ZDJECIE3: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Bochnia/Bochnia (3).jpg"),
}, {
    NAZWA: "II Królewskie Kopalnie Soli w Wieliczce i Bochni - Zamek Żupny w Wieliczce",
    NUMER_WPISU: "32ter",
    DATA_WPISU: "1978",
    MIEJSCOWOSC: "Wieliczka",
    N: 49.9838008522812,
    E: 20.0594275052337,
    OPIS: "Kopalnia Soli w Wieliczce, Kopalnia Soli w Bochni oraz Zamek Żupny w Wieliczce historycznie tworzyły królewskie przedsiębiorstwo Żupy Krakowskie, będące jednym z najstarszych zakładów przemysłowych na kontynencie. Obie kopalnie, które znajdują się w bliskim sąsiedztwie, w tym samym geologicznym złożu soli kamiennej, zarządzane były z Zamku Żupnego, który zajmował się m.in. sprzedażą soli na rzecz książąt oraz królów polskich, znacząco przyczyniając się do zwiększenia ich dochodów. Z tego też powodu Żupy Krakowskie oraz miasta, w których znajdowały się kopalnie, przez wiele lat otaczane były szczególną opieką monarchów. Miejsce posiada niekwestionowane wartości historyczne i naukowe, ponieważ działające nieprzerwanie od XIII do ostatnich lat XX w. kopalnie obrazują funkcjonowanie zakładów górniczych na przestrzeni dziejów i są świadectwem ewolucji technik wydobywania soli kamiennej. Dużą wartość edukacyjną przedstawia zachowany zbiór narzędzi i maszyn wykorzystywanych przez górników przy pracy. Obie kopalnie obejmują rozległy zespół chodników i komór zlokalizowanych na kilku poziomach, z których część sięga dużych głębokości. Zarówno w Wieliczce, jak i w Bochni, w wyrobiskach zachowało się wiele rzeźb oraz innych elementów dekoracyjnych wykonanych w soli kamiennej przez górników. Kunsztem artystycznym zachwycają przede wszystkim charakteryzujące się unikatowym, bogatym wystrojem i wyposażeniem podziemne kaplice. Warto szczególnie podkreślić długoletnią tradycję turystyczną kopalni, w których podziemne szlaki dla zwiedzających istnieją już od ponad 200 lat.",
    ZDJECIE1: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - Zamek Żupny/Wieliczka - Zamek Zupny (1).jpg"),
    ZDJECIE2: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - Zamek Żupny/Wieliczka - Zamek Zupny (2).jpg"),
    ZDJECIE3: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - Zamek Żupny/Wieliczka - Zamek Zupny (3).jpg"),
}, {
    NAZWA: "II Królewskie Kopalnie Soli w Wieliczce i Bochni - kopalnia soli w Wieliczce",
    NUMER_WPISU: "32ter",
    DATA_WPISU: "1978",
    MIEJSCOWOSC: "Wieliczka",
    N: 49.9808694411452,
    E: 20.0597573187163,
    OPIS: "Kopalnia soli w Wieliczce została uznana za pomnik historii w 1994 roku. Jest ona unikatowym obiektem górniczym, jednym z największych i najstarszych zakładów przemysłowych w Europie, czynnym nieprzerwanie od średniowiecza do końca XX wieku. Wraz z pobliską kopalnią w Bochni tworzyła Krakowskie Żupy Solne - historyczne przedsiębiorstwo o ogromnym znaczeniu dla gospodarki dawnej Rzeczypospolitej, którego zasady funkcjonowania określała XIV-wieczna ordynacja króla Kazimierza Wielkiego. Utrzymywana przez stulecia na najwyższym poziomie technicznym, stanowi dziś bezcenny dokument ewoluowania technik górniczych sprzed epoki maszyny parowej, a także rozwoju i organizacji przemysłu solnego w Polsce. Naukową wartość doskonale zachowanych wyrobisk, górniczych konstrukcji, urządzeń i narzędzi dopełniają źródła historyczne w postaci istniejącej dokumentacji ikonograficznej i kartograficznej z różnych epok. Na wyjątkowość wielickiej kopalni składa się ponadto naturalne piękno jej przestronnych komór, często zalanych jeziorami solankowymi, jak również oryginalny charakter obiektów sztuki i rzemiosła wykonanych w soli przez samych górników dla ozdobienia podziemnych kaplic. Podziwiana od stuleci przez odwiedzających ją, w tym liczne osobistości świata polityki, nauki i kultury, Wieliczka należy do najważniejszych miejsc tak polskiego, jak i światowego dziedzictwa kulturowego.",
    ZDJECIE1: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - kopalnia/Wieliczka - kopalnia (1).jpg"),
    ZDJECIE2: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - kopalnia/Wieliczka - kopalnia (2).jpg"),
    ZDJECIE3: require("./images/02. Królewskie Kopalnie Soli w Wieliczce i Bochni (wpis 1978, 2013)/Wieliczka - kopalnia/Wieliczka - kopalnia (3).jpg"),
}, {
    NAZWA: "III Auschwitz Birkenau - niemiecki nazistowski obóz koncentracyjny i Zagłady (1940-1945) - Auschwitz II",
    NUMER_WPISU: "31",
    DATA_WPISU: "1979",
    MIEJSCOWOSC: "Brzezinka",
    N: 50.0383202069881,
    E: 19.1704783396817,
    OPIS: "Obóz Birkenau był największym z ponad 40 obozów i podobozów wchodzących w skład kompleksu obozów Auschwitz. W czasie 3 lat istnienia pełnił on szereg funkcji: zaczęto go budować w październiku 1941 r. jako obóz dla około 125 000 jeńców wojennych, uruchomiono w marcu 1942 r. jako filię KL Auschwitz, przy czym pełnił równocześnie funkcję ośrodka zagłady Żydów. W ostatniej fazie istnienia, od 1944 r. stał się również miejscem koncentracji więźniów przed przeniesieniem ich do pracy dla niemieckiego przemysłu w głębi Trzeciej Rzeszy.\n" +
        "W obozie tym zginęła większość, przypuszczalnie około 90% ofiar KL Auschwitz, a zatem około 1 mln ludzi; w zdecydowanej większości (ponad 90%) byli to Żydzi. Ponadto w obozie tym zginęła znaczna część z około 70 000 Polaków zmarłych i zabitych w kompleksie obozów Auschwitz, około 20 000 Cyganów, oprócz nich jeńcy radzieccy i więźniowie innych narodowości.\n" +
        "Pierwsza wzmianka o zamiarze założenia obozu w Brzezince (Birkenau) wsi położonej w sąsiedztwie obozu koncentracyjnego Auschwitz związana jest z pierwszą wizytacją obozu Auschwitz przeprowadzoną przez Heinricha Himmlera w dniu 1 marca 1941 r. Jak zanotował w swojej autobiografii były komendant obozu Auschwitz, Rudolf Höss, w czasie tej wizytacji Himmler wydał szereg dyspozycji odnośnie rozbudowy istniejącego już obozu i zatrudnienia więźniów. Wśród nowo planowanych obiektów, które Himmler wymienił wówczas, znalazł się „obóz dla 100 000 jeńców wojennych”. Nie istnieją jednak dokumenty z tamtego okresu, które potwierdzałyby taką wersję wydarzeń.\n" +
        "Pierwsze projekty i plany obozu z jesieni 1941 r. przewidywały początkowo umieszczenie w obozie 100-125 000 ludzi. W 1942 roku koncepcja ta uległa kilkakrotnie zmianie – przyjęto mianowicie, że obóz ten będzie ostatecznie mieścił dwukrotnie więcej, bo 200 000 osób. Według tych planów obóz miał się dzielić na cztery części zwane odcinkami budowlanymi (Bauabschnitte), oznaczonymi kolejnymi cyframi rzymskimi: pierwszy odcinek budowlany miał mieścić 20 000 ludzi a pozostałe trzy odcinki po 60 000 ludzi. Cały obóz miał zajmować powierzchnię 175 hektarów.\n" +
        "W 1941 r. postanowiono, a w następnym roku uruchomiono w Brzezince, w sąsiedztwie budowanego obozu, urządzenia masowej zagłady – komory gazowe przeznaczone do masowego zabijania Żydów przywożonych do Brzezinki w ramach realizowanej przez władze Trzeciej Rzeszy całkowitej zagłady Żydów w Europie.\n",
    ZDJECIE1: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz II - Birkenau (1).jpg"),
    ZDJECIE2: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz II - Birkenau (2).jpg"),
    ZDJECIE3: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz II - Birkenau (3).jpg"),
},
    {
        NAZWA: "III Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady (1940-1945) - Auschwitz I",
        NUMER_WPISU: "31",
        DATA_WPISU: "1979",
        MIEJSCOWOSC: "Oświęcim",
        N: 50.0281036120721,
        E: 19.2036722862736,
        OPIS: "Obóz Auschwitz, którego zalążek stanowiły 22 murowane budynki przedwojennych koszar wojskowych, w miarę upływu czasu systematycznie rozrastał się przestrzennie i organizacyjnie. W szczytowym okresie swego rozwoju, latem 1944 r. obóz obejmował około 40 km2 terenu w bezpośrednim sąsiedztwie, i ponad 40 obozów filialnych rozrzuconych w promieniu kilkuset kilometrów. W tym czasie w kompleksie obozów Auschwitz przebywało około 135 tys. ludzi (105 tys. zarejestrowanych i około 30 tys. niezarejestrowanych), czyli 25% więźniów wszystkich obozów koncentracyjnych (525 tys.).\n" +
            "Biorąc pod uwagę funkcje, jakie pełnił ten obóz, można dojść do wniosku, że przeszedł on w ciągu blisko pięciu lat swego istnienia znamienną ewolucję: od koncepcji obozu kwarantanny, która legła u podstaw decyzji o założeniu obozu w 1940 r. (lecz nigdy nie weszła w stadium realizacji), poprzez obóz koncentracyjny − miejsce zagłady przede wszystkim w wyniku pozbawienia ludzi elementarnych warunków egzystencji, do nowego typu obozu stanowiącego połączenie obozu koncentracyjnego typu Dachau, czy Gross-Rosen, z ośrodkiem natychmiastowej zagłady typu Treblinka lub Bełżec.\n" +
            "Z uwagi na podstawowe funkcje, jakie pełnił KL Auschwitz, w jego historii można wyróżnić dwa zasadnicze okresy:\n" +
            "1.\tod założenia obozu w 1940 r. i przywiezienia pierwszego transportu Polaków, więźniów politycznych 14 czerwca 1940 r. aż do pierwszych miesięcy 1942 r., kiedy pełnił on wyłącznie funkcję obozu koncentracyjnego, czyli miejsca w przeważającej mierze powolnej zagłady, będącej wynikiem celowo stworzonych warunków nieludzkiej egzystencji, przede wszystkim zaś głodu;\n" +
            "2.\tod pierwszych miesięcy 1942 r. do października 1944 r., kiedy obóz ten pełniąc nadal funkcję obozu koncentracyjnego dla więźniów różnych narodowości (od połowy 1942 r. głównie Żydów, Polaków, Cyganów), równocześnie pełnił funkcję największego ośrodka natychmiastowej, masowej zagłady Żydów przywożonych tutaj w ramach akcji zagłady ludności żydowskiej z całej Europy.\n" +
            "W ostatnich dwóch miesiącach istnienia, po unieruchomieniu w październiku 1944 r. komór gazowych, w związku z krytyczną sytuacją militarną Trzeciej Rzeszy i spodziewaną kolejną ofensywą radziecką, obóz wszedł w stadium ostatecznej likwidacji zakończonej ewakuacją więźniów.\n",
        ZDJECIE1: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz I (1).jpg"),
        ZDJECIE2: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz I (2).jpg"),
        ZDJECIE3: require("./images/04. Auschwitz Birkenau, niemiecki nazistowski obóz koncentracyjny i zagłady 1940-1945 (wpis 1979)/Auschwitz I (3).jpg"),
    },
    {
        NAZWA: "IV Puszcza Białowieska",
        NUMER_WPISU: "33ter",
        DATA_WPISU: "1979",
        MIEJSCOWOSC: "Białowieża",
        N: 52.7538586935794,
        E: 23.7355722793155,
        OPIS: "Puszcza Białowieska to duży kompleks leśny zlokalizowany na pograniczu Polski i Białorusi. Dzięki trwającej od kilku wieków ochronie, Puszcza zachowała swój pierwotny charakter po dziś dzień. Białowieski Park Narodowy, Polska, został wpisany na Listę Światowego Dziedzictwa w 1979 r., natomiast w 1992 r. obszar ten został rozszerzony o białoruską część Puszczy Białowieskiej. Wskutek znaczącego rozszerzenia miejsca w 2014 r. obejmuje on obecnie obszar 141 885 ha wraz ze strefą buforową o powierzchni 166 708 ha.\n" +
            "Obiekt obejmuje kompleks lasów nizinnych, charakterystycznych dla ekoregionu lasów mieszanych Środkowej Europy. Obszar ten ma wyjątkowe znaczenie dla ochrony przyrody z uwagi na powierzchnię starodrzewi obejmujących duże nietknięte obszary, na których zachodzą procesy naturalne. Ich rezultatem jest bogactwo martwych drzew – zarówno stojących jak i leżących, przekładające się na  dużą różnorodność gatunków grzybów i bezkręgowców saproksylicznych. Obiekt zapewnia ochronę różnorodnej i bogatej fauny, obejmującej 59 gatunków ssaków, ponad 250 gatunków ptaków, 13 gatunków płazów, 7 gatunków gadów i ponad 12 000 gatunków bezkręgowców. Symbolem obiektu jest żubr: na całym terenie zamieszkuje około 900 osobników, co stanowi prawie 25% światowej populacji żubra i ponad 30% wolno żyjących zwierząt.\n",
        ZDJECIE1: require("./images/03. Belovezhskaya Pushcha - Puszcza Białowieska (wpis 1979, 1992, 2014)/Puszcza Bialowieska (1).jpg"),
        ZDJECIE2: require("./images/03. Belovezhskaya Pushcha - Puszcza Białowieska (wpis 1979, 1992, 2014)/Puszcza Bialowieska (2).jpg"),
        ZDJECIE3: require("./images/03. Belovezhskaya Pushcha - Puszcza Białowieska (wpis 1979, 1992, 2014)/Puszcza Bialowieska (3).jpg"),
    }, {
        NAZWA: "V Historyczne centrum Warszawy",
        NUMER_WPISU: "30bis",
        DATA_WPISU: "1980",
        MIEJSCOWOSC: "Warszawa",
        N: 52.2492804757072,
        E: 21.0135486885606,
        OPIS: "Warszawa została w 1944 r. celowo unicestwiona w drodze represji za opór stawiony niemieckiej okupacji. Obrócenie w ruinę stolicy kraju miało przekreślić wielowiekową tradycję państwowości polskiej. Odbudowa historycznego miasta, zburzonego w 85%, była możliwa dzięki determinacji mieszkańców i pomocy całego narodu. Rekonstrukcja Starego Miasta, w jego historycznym urbanistycznym i architektonicznym kształcie, była przejawem troski o zapewnienie przetrwania jednego z najważniejszych świadectw kultury polskiej. Miasto – symbol władzy elekcyjnej i tolerancji, miejsce uchwalenia pierwszej demokratycznej konstytucji europejskiej, zwanej Konstytucją 3 Maja z 1791 r., zostało odbudowane. Rekonstrukcja objęła całościowe odtworzenie urbanistycznego planu wraz z Rynkiem Starego Miasta, kamienicami mieszczańskimi, pierścieniem murów obronnych, Zamkiem Królewskim oraz znaczącymi budowlami sakralnymi.\n" +
            "Rekonstrukcja historycznego centrum Warszawy była głównym czynnikiem zmian doktryn związanych z rozwiązywaniem problemów urbanistycznych i konserwacją zabudowy miejskiej w większości europejskich krajów po zniszczeniach II wojny światowej. Jednocześnie przykład ten pokazuje skuteczność działań konserwatorskich II połowy XX wieku, umożliwiających integralną rekonstrukcję złożonego zespołu miejskiego.\n" +
            "Odbudowa Starego Miasta była prowadzona w oparciu o spójny i konsekwentnie zrealizowany projekt opracowany w Biurze Odbudowy Stolicy w latach 1945-1951. Projekt odbudowy oparto na założeniu, że wykorzystane zostaną zachowane, niezniszczone w czasie działań wojennych struktury powstałe pomiędzy XIV i XVIII wiekiem, wraz z późnośredniowieczną siatką ulic z placami i rynkiem oraz pierścieniem murów miejskich. Przy odtwarzaniu zniszczonej zabudowy kierowano się dwiema głównymi zasadami: po pierwsze, aby wykorzystywać wiarygodne dokumenty archiwalne oraz po drugie, aby odtworzyć obraz historycznego miasta z końca XVIII w. Koncepcja odbudowy była uzależniona od dostępności szczegółowych materiałów ikonograficznych i dokumentacji historycznych z tego okresu. Wykorzystano także inwentaryzacje konserwatorskie wykonane przed 1939 i po 1944 roku oraz wiedzę naukowo-badawczą historyków sztuki, architektów i konserwatorów. Archiwum Biura Odbudowy Stolicy, zawierające zarówno dokumentację zniszczeń, jak i projekty odbudowy, w 2011 roku zostało wpisane na Listę Pamięci Świata UNESCO.\n" +
            "Odbudowa Starego Miasta była prowadzona do połowy lat 60. XX wieku. Cały proces zakończyła odbudowa Zamku Królewskiego (otwartego dla zwiedzających w roku 1984). Rekonstrukcja poszczególnych budowli i ich otoczenia w przyjętej formule osiedla mieszkaniowego z funkcjami publicznymi dedykowanymi kulturze i nauce oraz usługami, niosła za sobą wiele wyzwań związanych z adaptacją do wówczas obowiązujących norm i wymogów cywilizacyjnych. W celu uczytelnienia murów obronnych i panoramy miasta od strony Wisły, w trakcie działań świadomie zrezygnowano z odtworzenia części budynków. Zachowano układ urbanistyczny z podziałem pierzei na historyczne działki budowlane, jednak nie odtworzono zabudowy wewnątrz kwartałów, tworząc wspólne tereny otwarte dla mieszkańców. Układ wewnętrzny budynków i lokali mieszkalnych został dostosowany do obowiązujących ówcześnie standardów. Natomiast w wielu budynkach i lokalach przeznaczonych na funkcje publiczne odtworzono zarówno historyczne układy pomieszczeń, jak i wystrój wnętrz. Dużą wartość przedstawiają dekoracje elewacji wykonane przez zespół wybitnych artystów, w części nawiązujące do projektów z okresu międzywojennego. Polichromie wykonano w tradycyjnych technikach w tym sgraffita. Mimo adaptacji i wprowadzonych zmian, Miejsce to wraz z panoramą od strony Wisły (mającą rangę symbolu Warszawy), prezentuje spójny obraz najstarszej części miasta.\n" +
            "Zespolenie ocalałych elementów z częściami Starego Miasta odtworzonymi w wyniku programu działań konserwatorskich doprowadziło do powstania przestrzeni miejskiej wyjątkowej w wymiarze materialnym (forma najstarszej części miasta), funkcjonalnym (dzielnica mieszkalna i miejsce ważnych wydarzeń historycznych, społecznych i duchowych) oraz symbolicznym (miasto nieujarzmione).\n",
        ZDJECIE1: require("./images/05. Historyczne centrum Warszawy (wpis 1980)/Warszawa (1).jpg"),
        ZDJECIE2: require("./images/05. Historyczne centrum Warszawy (wpis 1980)/Warszawa (2).jpg"),
        ZDJECIE3: require("./images/05. Historyczne centrum Warszawy (wpis 1980)/Warszawa (4).jpg"),
    }, {
        NAZWA: "VI Stare Miasto w Zamościu",
        NUMER_WPISU: "564",
        DATA_WPISU: "1992",
        MIEJSCOWOSC: "Zamość",
        N: 50.7156370200422,
        E: 23.2516777549434,
        OPIS: "Stare Miasto w Zamościu jest unikatowym przykładem miasta renesansowego w Europie Centralnej, konsekwentnie ukształtowanego według włoskich teorii „miasta idealnego”, na podstawie planu, stanowiącego rezultat modelowej współpracy światłego fundatora Jana Zamoyskiego i wybitnego architekta Bernarda Morando. Stare Miasto w Zamościu dziś zachowuje swój pierwotny prostoliniowy układ ulic i jego unikalną mieszankę tradycji architektonicznych włoskich i Europy Środkowej, a także fragmenty otaczających je fortyfikacji.\n" +
            "Położony na szlaku handlowym łączącym zachodnią i północną Europę z Morzem Czarnym, Zamość został stworzony od początku jako ośrodek ekonomiczny oparty na handlu. W mieście z założenia wielonarodowościowym jego społeczność charakteryzowała się wielką tolerancją religijną. Zamość jest materialną emanacją społecznych i kulturalnych idei Odrodzenia, które znalazły w Polsce żywy oddźwięk, czego dopełnieniem było utworzenie przez założyciela i właściciela miasta Jana Zamoyskiego – Akademii Zamoyskiej. Plan miasta autorstwa Bernarda Moranda łączy funkcje zespołu miejskiego, rezydencji i fortecy według konsekwentnie realizowanej koncepcji renesansowej.\n" +
            "Stare Miasto w Zamościu składa się z dwóch odrębnych części: na zachodzie pałacu Zamoyskich, na wschodzie miasta właściwego, rozmieszczonego wokół trzech kwadratów. Usytuowany centralnie Rynek Wielki, położony u zbiegu dwóch głównych osiowych ulic miasta, jest otoczony przez domy podcieniowe kuców oraz zakotwiczony wspaniałym ratuszem. Te i wiele innych znaczących budowli, takich jak katedra, arsenał, czy fortyfikacje z bramami ilustrują kluczową cechę tego rozległego założenia: jego twórcze wzbogacenie artystycznymi osiągnięciami architektury rodzimej. Konsekwentnym rezultatem planu Moranda jest stworzenie jednolitej stylowo kompozycji urbanistycznej o wysokich walorach architektonicznych oraz krajobrazowych.\n",
        ZDJECIE1: require("./images/06. Stare miasto w Zamościu (wpis 1992)/Zamosc (1).jpg"),
        ZDJECIE2: require("./images/06. Stare miasto w Zamościu (wpis 1992)/Zamosc (2).jpg"),
        ZDJECIE3: require("./images/06. Stare miasto w Zamościu (wpis 1992)/Zamosc (4).jpg"),
    }, {
        NAZWA: "VII Miasto średniowieczne w Toruniu",
        NUMER_WPISU: "835",
        DATA_WPISU: "1997",
        MIEJSCOWOSC: "Toruń",
        N: 53.0106994511999,
        E: 18.6067012336235,
        OPIS: "Toruń leżący na północy Polski jest wyjątkowo dobrze zachowanym przykładem średniowiecznego centrum handlowego i administracyjnego o znaczeniu europejskim, położonym nad Wisłą. Toruń założono w czasie kiedy rycerze Zakonu Krzyżackiego szerzyli chrześcijaństwo pośród ludów Europy Wschodniej oraz kiedy Liga Hanzeatycka przyczyniała się do gwałtownego rozwoju handlu pomiędzy krajami nadbałyckimi i Europą Wschodnią. Toruń stał się wiodącym członkiem Ligi Hanzeatyckiej na terenach znajdujących się pod panowaniem Zakonu Krzyżackiego.\n" +
            "Średniowieczne miasto w Toruniowi składa się z trzech elementów: ruin zamku krzyżackiego, Starego Miasta oraz Nowego Miasta. Dwa miasta oraz zamek, zabudowane w kształcie podkowy, otoczone murami miejskimi stanowią wyjątkową formę średniowiecznego rozkładu zabudowań. Większa część zamku, który został zbudowany na rzucie podkowy w połowie XIII wieku jako baza do podboju i ewangelizacji Prus, została zniszczona podczas powstania w 1454 roku, kiedy miejscowi mieszczanie podnieśli się przeciwko Zakonowi Krzyżackiemu. Ruiny i archeologiczne pozostałości zostały odkopane i zachowane. Stare Miasto zostało lokowane w roku 1233, po czym szybko rozwinęło się jako ważny ośrodek handlu. Sąsiadujące Nowe Miasto rozwijało się od 1264 roku, głównie jako ośrodek rzemiosła i rękodzielnictwa. Oba obszary miejskie świadczą o wymianie i twórczej adaptacji doświadczeń artystycznych, które miały miejsce wśród miast hanzeatyckich.\n" +
            "Wyjątkowo pełny obraz średniowiecznego sposobu życia jest widoczny w oryginalnym układzie ulic i pierwszych budynków Torunia. Zarówno Stare jak i Nowe Miasto posiadają swoje kościoły parafialne oraz liczne piękne ceglane kamienice, spośród których wiele zachowało oryginalne gotyckie elewacje, ściany działowe, stropy zdobione sztukaterią, sklepione podpiwniczenia i malowane zdobienia. Wiele budynków w Toruniu było wykorzystywanych zarówno dla celów mieszkalnych jak i handlowych. Dobrym przykładem jest dom, w którym w 1473 roku urodził się wielki astronom Mikołaj Kopernik, zachowany jako muzeum poświęcone temu wielkiemu człowiekowi i jego pracy. Kamienice często obejmowały pomieszczenia magazynowe i niezwykle spichlerze wykonane z cegły, niektóre wysokie nawet na pięć pięter. Ponieważ zachowało się tak wiele budynków z tego okresu średniowieczny podział na parcele, wyznaczony przez oryginalne mury ogrodzeniowe z cegły, został w znacznej części zachowany.\n",
        ZDJECIE1: require("./images/07. Miasto średniowieczne w Toruniu (wpis 1997)/Torun (1).jpg"),
        ZDJECIE2: require("./images/07. Miasto średniowieczne w Toruniu (wpis 1997)/Torun (3).jpg"),
        ZDJECIE3: require("./images/07. Miasto średniowieczne w Toruniu (wpis 1997)/Torun (4).jpg"),
    }, {
        NAZWA: "VIII Zamek krzyżacki w Malborku",
        NUMER_WPISU: "847",
        DATA_WPISU: "1997",
        MIEJSCOWOSC: "Malbork",
        N: 54.0412753376652,
        E: 19.0302002831103,
        OPIS: "Zamek Malbork położony jest na północy Polski, na wschodnim brzegu rzeki Nogat. Stanowi najpełniejszy i najbardziej złożony przykład gotyckiego zespołu zamkowego z cegły, w charakterystycznym, unikalnym stylu budownictwa zakonu krzyżackiego. Styl ten rozwijał się niezależnie od tych, jakie dominowały ówcześnie na Zachodzie Europy i na Bliskim Wschodzie.\n" +
            "Ta potężna warownia jest materialnym świadectwem niezwykłego zjawiska, jakim było państwo zakonne w Prusach. Państwo utworzyli w XIII wieku niemieccy mnisi-rycerze, prowadzący krucjaty przeciwko pogańskim Prusom i Litwinom, osiadłym na południowym wybrzeżu Bałtyku, a także przeciwko chrześcijańskiemu Królestwu Polskiemu. Swoją świetność osiągnął w stuleciu XIV. Zamek-klasztor nad Nogatem stanowi więc znak dramatu późnośredniowiecznego chrześcijaństwa, z charakterystycznym dlań napięciem pomiędzy pragnieniem świętości a posługiwaniem się przemocą.\n" +
            "Od drugiej połowy XVIII wieku zamek Malbork był jednym z najważniejszych źródeł fascynacji historią europejskiego średniowiecza i jego pozostałościami. Jego niedawna przeszłość ilustruje tendencję do traktowania historii i jej zabytków jako narzędzi w służbie ideologii politycznych.\n" +
            "Od XIX wieku do dzisiaj malborski zespół zamkowy pozostaje przedmiotem prac konserwatorskich, które w wyjątkowy sposób wpływały na rozwój badań naukowych oraz teorii i praktyki konserwatorskiej w tej części świata. W trakcie owych działań odtworzono wiele średniowiecznych technik artystycznych i rzemieślniczych. Szeroko zakrojone prace konserwatorskie przeprowadzono w XIX i na początku XX wieku. Po ciężkich zniszczeniach, którym uległ w końcowej fazie II wojny światowej, zamek został ponownie zrekonstruowany.\n" +
            "Zamek Malbork, poza istnieniem w swojej substancji materialnej, jest też głęboko obecny w społecznej świadomości, jako nasycony emocjami, ważny znak historii Europy Środkowej.\n",
        ZDJECIE1: require("./images/08. Zamek krzyżacki w Malborku (wpis 1997)/Malbork (1).jpg"),
        ZDJECIE2: require("./images/08. Zamek krzyżacki w Malborku (wpis 1997)/Malbork (3).jpg"),
        ZDJECIE3: require("./images/08. Zamek krzyżacki w Malborku (wpis 1997)/Malbork (4).jpg"),
    }, {
        NAZWA: "IX Kalwaria Zebrzydowska - manierystyczny zespół architektoniczno-krajobrazowy oraz park pielgrzymkowy",
        NUMER_WPISU: "905",
        DATA_WPISU: "1999",
        MIEJSCOWOSC: "Kalwaria Zebrzydowska",
        N: 49.8544929880726,
        E: 19.6830133931174,
        OPIS: "Kalwaria Zebrzydowska: manierystyczny zespół architektoniczno-krajobrazowy oraz park pielgrzymkowy, którego początki sięgają pierwszej połowy XVII w., to krajobraz kulturowy zlokalizowany na południe od Krakowa, który obejmuje obszar gór Żar i Lanckorońskiej. To niezwykłe świadectwo religijności i kultury było pierwszym założeniem typu \"wielkich kalwarii\" w Polsce i stało się pierwowzorem dla licznych późniejszych realizacji. Wśród kalwarii europejskich wyróżnia się indywidualizmem rozwiązań i szczególnym zespoleniem „sacrum” z naturą oraz nieprzerwaną tradycją odprawianych tu misteriów. To sanktuarium pasyjno-maryjne jest wybitnym przykładem realizacji idei kalwarii w dobie kontrreformacji, która przyczyniła się do rozwoju pobożności w formie ruchu pielgrzymkowego. Park pielgrzymkowy, ogród modlitwy, jest ściśle związany z treściami Męki Pańskiej i życia Matki Boskiej.\n" +
            "Pomysłodawcą i fundatorem założenia był Mikołaj Zebrzydowski, wojewoda krakowski i starosta lanckoroński, który zatrudnił Feliksa Żebrowskiego, wybitnego matematyka, astronoma i geodetę aby stworzył kopię Jerozolimy takiej, jak wierzono, że istniała za czasów Chrystusa. Korzystając z systemu pomiarów, który opracował, wpisał ją w naturalny krajobraz i lokalną topografię. Umiejętnie wykorzystano tu naturalne cechy terenu, nadając elementom topografii nazwy odwołujące się do krajobrazu Świętego Miasta (np. Dolina Cedronu, Góra Oliwna, Golgota) i dopełniając je budowlami, które są połączone ścieżkami i trzyrzędowymi alejami drzew, symbolizującymi starożytne drogi.\n" +
            "Charakterystyczne cechy parków i ogrodów projektowanych w stylu włoskiego renesansu i francuskiego baroku stapiają się tu z manierystyczną wolnością i nieregularnością. Stąd też występowanie licznych osi widokowych pomiędzy różnymi elementami kompozycji, jak również serii wspaniałych panoram nie tylko samego parku, ale także Tatr czy Krakowa.\n" +
            "Zespół sakralny składa się z klasztoru z Bazyliką oraz kilkudziesięciu kościołów, kaplic i innych obiektów architektonicznych. Budowle, których forma reprezentuje najwyższe wartości artystyczne manieryzmu wzniesiono w latach 1605-1632, z których 14 pierwszych kaplic jest autorstwa Pawła Baudartha. Pozostałe powstawały sukcesywnie od XVII do początku XX w. Dróżki pielgrzymkowe łączące obiekty architektoniczne pierwotnie zostały wyznaczone poprzez wycięcie szerokich traktów w zwartym drzewostanie leśnym. Z powodu wycinki drzew z czasem krajobraz stawał się coraz bardziej otwarty. Dlatego też w XVIII w., aby trwale wydzielić na terenach otwartych dróżki w ich pierwotnym rozplanowaniu, obsadzono je alejami drzew, co wzbogaciło kompozycję przestrzenną Kalwarii.\n" +
            "Architektura parku pielgrzymkowego oraz krajobraz komponowany stanowią również plenerową scenografię dla misteriów Drogi Krzyżowej i Pogrzebu Matki Bożej, które są tu odprawiane nieprzerwanie od początku XVII w., od ponad 400 lat, z udziałem wielotysięcznej rzeszy pielgrzymów i turystów.\n",
        ZDJECIE1: require("./images/09. Kalwaria Zebrzydowska - manierystyczny zespół architektoniczno-krajobrazowy oraz park pielgrzymkowy (wpis 1999)/Kalwaria (1).jpg"),
        ZDJECIE2: require("./images/09. Kalwaria Zebrzydowska - manierystyczny zespół architektoniczno-krajobrazowy oraz park pielgrzymkowy (wpis 1999)/Kalwaria (3).jpg"),
        ZDJECIE3: require("./images/09. Kalwaria Zebrzydowska - manierystyczny zespół architektoniczno-krajobrazowy oraz park pielgrzymkowy (wpis 1999)/Kalwaria (4).jpg"),
    }, {
        NAZWA: "X Kościoły Pokoju w Jaworze i Świdnicy - Kościół Pokoju w Jaworze",
        NUMER_WPISU: "1054",
        DATA_WPISU: "2001",
        MIEJSCOWOSC: "Jawor",
        N: 51.0539125770285,
        E: 16.1891299255947,
        OPIS: "Drewniany kościół ewangelicki o konstrukcji szachulcowej, usytuowany w mieście Jawor, jest zabytkowym budynkiem sakralnym wybudowanym na mocy porozumień pokoju westfalskiego zawartego w 1648 i kończącego wojnę trzydziestoletnią.\n" +
            "Został wybudowany w latach 1654–1655 według projektu Albrechta von Säbischa z zastosowaniem konstrukcji ryglowej. Budowla powstała z materiałów nietrwałych: drewna, słomy i gliny. Na uwagę zasługuje barokowe wyposażenie wnętrza: ołtarz, ambona i chrzcielnica. Po stronie północnej i południowej wzniesiono po cztery kondygnacje empor, których parapety zdobią obrazy ilustrujące Stary i Nowy Testament oraz pejzaże z zamkami i tarcze heraldyczne. Wszystkie elementy konstrukcyjne pokrywają polichromie o motywach fantazyjnie zwiniętych wici roślinnych. Ten obiekt wyróżnia się na tle historii sztuki europejskiej II połowy XVII w. ze względu na swą unikatowość i wysokie walory artystyczne. Jest jednym z trzech tzw. Kościołów Pokoju wybudowanych po wojnie trzydziestoletniej i jednym z dwóch zachowanych do dziś (drugi w Świdnicy).\n",
        ZDJECIE1: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Jawor/Jawor (1).jpg"),
        ZDJECIE2: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Jawor/Jawor (3).jpg"),
        ZDJECIE3: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Jawor/Jawor (5).jpg"),
    }, {
        NAZWA: "X Kościoły Pokoju w Jaworze i Świdnicy - Kościół Pokoju w Świdnicy",
        NUMER_WPISU: "1054",
        DATA_WPISU: "2001",
        MIEJSCOWOSC: "Świdnica",
        N: 50.8464967382446,
        E: 16.4916801534818,
        OPIS: "Powstał na mocy pokoju westfalskiego (stąd nazwa), kończącego wojnę trzydziestoletnią 1618-1648. Przed jej rozpoczęciem świdniczanie mogli swobodnie wyznawać idee Lutra, w mieście odprawiano nabożeństwa luterańskie.\n" +
            "Po wybuchu wojny ewangelikom odebrano prawo do własnej wiary i kościołów. Zgodnie z pokojem westfalskim, katolicki cesarz Ferdynand III Habsburg został zobowiązany przez Szwedów do zezwolenia ewangelikom w księstwach dziedzicznych w Jaworze, Głogowie i Świdnicy na zbudowanie po jednym tzw. Kościele Pokoju. Habsburgowie surowo obwarowali tę zgodę: ewangelicy mogli wznieść świątynię wyłącznie poza murami miasta, bez wież i dzwonnicy, tylko z nietrwałych materiałów – z drewna, piasku, słomy i gliny. Nie mogła przypominać kościoła, a jej budowa nie mogła przekroczyć roku.\n" +
            "Ewangelicy wykazali się wówczas niezwykłą zaradnością, najbiedniejsi przynosili choćby deskę. W budowę zaangażowali się przedstawiciele wszystkich stanów, od szlachty, przez mieszczaństwo, po chłopów. Świdniczanin Christian Czepko wyruszył w podróż po europejskich dworach protestanckich, żeby prosić o pieniądze na budowę. Udało się i w1657 r. odprawiono pierwsze nabożeństwo w Kościele Pokoju w Świdnicy. Dwa takie kościoły powstały także w Głogowie (spłonął po stu latach) oraz w Jaworze (istnieje do dziś).\n",
        ZDJECIE1: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Świdnica/Swidnica (1).jpg"),
        ZDJECIE2: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Świdnica/Swidnica (3).jpg"),
        ZDJECIE3: require("./images/10. Kościoły Pokoju w Jaworze i Świdnicy (wpis 2001)/Świdnica/Swidnica (5).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. św. Leonarda w Lipnicy Murowanej",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Lipnica Murowana",
        N: 49.8603020215848,
        E: 20.5311510994537,
        OPIS: "Tradycje odnoszą wzniesienie kościoła do r. 1141 lub 1203, kiedy miał stanąć w miejscu pogańskiej gontyny. Faktycznie kościół wzniesiono pod koniec XV w., zastępując wcześniejszą świątynię. O odległej metryce świadczy wezwanie św. Leonarda, którego kult rozpowszechnił się tu w XII-XIII w. Pierwsza wzmianka pisana pochodzi dopiero z wizytacji biskupiej w 1570. Zniszczenia wojen szwedzkich w XVII w. ominęły kościół.\n" +
            "Świątynia była wielokrotnie odnawiana, co nie wpłynęło znacząco na jej bryłę i układ przestrzenny. W XVI w. wykonano ornamentalną polichromię stropu prezbiterium. Ściany prezbiterium malowano w r. 1689, nawy w 1710–1711. W XVII w. kościół opasano sobotami. W 1872 wylew rzeczki Uszwicy uszkodził świątynię. Prace konserwatorskie przeprowadzono w 1910. W 1997 powódź naruszyła fundamenty budowli, woda zalała cmentarz. Do 2000 trwały kompleksowe prace konserwatorskie.\n",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Lipnica Murowana/Lipnica Murowana (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Lipnica Murowana/Lipnica Murowana (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Lipnica Murowana/Lipnica Murowana (3).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. św. Michała Archanioła w Binarowej",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Binarowa",
        N: 49.7574545922324,
        E: 21.2270951396882,
        OPIS: "Kościół po raz pierwszy odnotowany został w r. 1415, obecny wzniesiono ok. 1500 r. W r. 1596 od zachodu do jego nawy dostawiono wieżę, a na początku XVII w. otoczono go sobotami. W okresie 1602–1608 wzniesiono wieżyczkę na sygnaturkę. W latach 1641–1650, na fali kontrreformacyjnej działalności Kościoła, dokonano gruntownej przebudowy: do nawy od północy dostawiono kaplicę Aniołów Stróżów, a wieża otrzymała nowe zwieńczenie; przekształceniu uległo też wnętrze świątyni, przebudowano chór muzyczny, powiększono otwory okienne, w miejsce wcześniejszej polichromii patronowej na ścianach wykonano nową, figuralną dekorację malarską. W czasie remontu w r. 1892 rozbudowano przyziemie wieży. Po 1908 dachy nawy i prezbiterium oraz górne partie wieży pokryte zostały blachą ocynkowaną, szalunek gontowy ścian zastąpiono deskowaniem, a zaskrzynienia w nawie podparto arkadami filarowymi. Od lat dziewięćdziesiątych XX w. prowadzone są prace nad przywróceniem stanu kościoła sprzed r. 1908.",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Binarowa/Binarowa (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Binarowa/Binarowa (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Binarowa/Binarowa (3).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. św. Filipa i św. Jakuba w Sękowej",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Sękowa",
        N: 49.6306453339078,
        E: 21.187001063962,
        OPIS: "Kościół pw. Świętych Filipa i Jakuba zbudowany został ok. 1520 r. W XVIII w. powstała niska wieża, wieżyczka na sygnaturkę i wysokie soboty. Przed r. 1819 przebudowano zakrystię i chór muzyczny. Przed 1888 ściany i strop we wnętrzu pokryto neogotycką polichromią figuralną. W 1885 kościół utracił status świątyni parafialnej, po wybudowaniu w Sękowej murowanego kościoła. Na przełomie XIX i XX w. kościół był dokumentowany, jako cenny przykład ciesiołki gotyckiej. W czasie I wojny światowej uszkodzony, remontowany po 1918. Dalsze prace w 2 poł. XX w. W 1994 za wzorowo prowadzone prace konserwatorskie świątyni i jej opiekunowi przyznano medal Prix Europa Nostra. W 2003 wpisany na Listę Światowego Dziedzictwa UNESCO.",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Sękowa/Sekowa (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Sękowa/Sekowa (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Sękowa/Sekowa (3).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. św. Michała Archanioła w Dębnie",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Dębno",
        N: 49.4663386696461,
        E: 20.2116266456755,
        OPIS: "W przywileju lokacyjnym wsi Dębno z 1335 odnotowano najstarszą wzmiankę o kościele (choć niewątpliwie istniał on wcześniej), który w 1400 uzyskał status parafialny. Obecny kościół, drugi na tym samym miejscu, wzniesiono w 2. połowie XV w.; datację potwierdzają badania dendrochronologiczne, stwierdzające jednolity czas budowy korpusu wraz z konstrukcją dachową. Budowla średniowieczna była bezwieżowa. Wieżę dobudowano, w odmiennej od korpusu konstrukcji, w 1601, co potwierdza odnaleziony przez fragment inskrypcji. Do elementów dodanych w XVII w. należą obiegające kościół soboty oraz kruchta południowa. Badacze zabytków „odkryli” kościół w Dębnie pod koniec XIX w. Gruntowny remont, obejmujący także konserwację malowideł ściennych, nastąpił w latach 1933–1935. Kompleksowe zabiegi konserwatorskie zrealizowano w latach 1958–1963. W r. 1999 kompleksowej analizie naukowej poddano stan zachowania kościoła, ze szczególnym zwróceniem uwagi na stan unikatowej dekoracji malarskiej wnętrza.",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Dębno Podhalańskie/Debno Podhalanskie (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Dębno Podhalańskie/Debno Podhalanskie (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Dębno Podhalańskie/Debno Podhalanskie (3).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. Wniebowzięcia Najświętszej Maryi Panny i św. Michała Archanioła w Haczowie",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Haczów",
        N: 49.6705245722787,
        E: 21.8894132238349,
        OPIS: "Kościół należy do najstarszych i największych gotyckich kościołów drewnianych konstrukcji zrębowej w Europe. Świątynia odznacza się wyjątkowym monumentalizmem bryły, charakterystyczną formą architektoniczną i doskonałością rozwiązań konstrukcyjnych. Obok wartości architektonicznej duże znaczenie posiada zachowany bogaty wystrój malarski wnętrza o ciekawym programie ikonograficzno-ideowym i wysokim poziomie artystycznym, z unikatową gotycką polichromią figuralną z ok. 1494 r. Świątynia jest wybitnym przykładem średniowiecznej drewnianej architektury sakralnej Małopolski. Wpis kościoła (jako jednego z sześciu drewnianych kościołów południowej Małopolski) na Listę światowego dziedzictwa UNESCO potwierdził uznanie jego wyjątkowej wartości w skali świata.",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Haczów/Haczow (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Haczów/Haczow (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Haczów/Haczow (3).jpg"),
    }, {
        NAZWA: "XI Kościoły drewniane południowej Małopolski - Kościół pw. Wszystkich Świętych w Bliznem",
        NUMER_WPISU: "1053rev",
        DATA_WPISU: "2003",
        MIEJSCOWOSC: "Blizne",
        N: 49.7506243200315,
        E: 21.9762946648625,
        OPIS: "Kościół w Bliznem jest jednym z najcenniejszych obiektów średniowiecznej drewnianej architektury sakralnej w Polsce. O jego wyjątkowym znaczeniu decyduje zarówno doskonale zachowana substancja architektoniczna (m. in. niemal w stu procentach zachowana oryginalna XV-wieczna konstrukcja zrębu ścian oraz storczykowej więźby dachowej z ciesielskimi znakami montażowymi), niezwykle bogate wyposażenie ruchome, powstałe na przestrzeni od XVI do XIX w., jak też unikatowy zespół malowideł ściennych z XV-XVIII w. W bezpośrednim otoczeniu kościoła znajduje się zespół zabytkowych XIX-wiecznych, drewnianych zabudowań plebańskich. Całość tworzy wyjątkowo cenny zespół kościelno-plebański, malowniczo wpisany w krajobraz doliny Stobnicy. Kościół wpisany jest na Listę światowego dziedzictwa UNESCO.",
        ZDJECIE1: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Blizne/Blizne (1).jpg"),
        ZDJECIE2: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Blizne/Blizne (2).jpg"),
        ZDJECIE3: require("./images/11. Kościoły drewniane południowej Małopolski Binarowa, Blizne, Dębno, Sękowa, Haczów, Lipnica Murowana (wpis 2003)/Blizne/Blizne (3).jpg"),
    }, {
        NAZWA: "XII Park Mużakowski/Muskauer Park",
        NUMER_WPISU: "1127",
        DATA_WPISU: "2004",
        MIEJSCOWOSC: "Łęknica",
        N: 51.5513636214017,
        E: 14.7376466775564,
        OPIS: "Park Mużakowski to rozległy park krajobrazowy założony w latach 1815-1844 przez księcia von Pückler-Muskau, na obszarze jego posiadłości, rozwijany przez Eduarda Petzolda, wybitnego ucznia Pücklera. Park harmonijnie wpisuje się w dolinę Nysy Łużyckiej, integrując zabudowę miasta z krajobrazem rolniczym, co stanowiło zapowiedź nowego podejścia do projektowania krajobrazu i miało wpływ na rozwój „architektury krajobrazu” jako dyscypliny. To rozległe założenie obejmuje rzekę Nysę, inne elementy wodne, zarówno sztuczne, jak i naturalne, mosty, budynki, zadrzewienia oraz ścieżki. Jest to przykład krajobrazu wykreowanego przez człowieka, w którym w mistrzowski sposób zostały wykorzystane walory przyrodnicze miejsca.\n" +
            "Park o wysoce estetycznej kompozycji harmonijnie wpisuje się w naturalne ukształtowanie doliny rzeki. Jej istotą jest powiązanie widokowe centrum rezydencji, Nowego Zamku, z szeregiem topograficznych „punktów kulminacyjnych”, które stanowią idealne punkty widokowe, rozmieszczone wzdłuż tarasów rzecznych po obu stronach doliny, z których każdy jest częścią misternej sieci widoków. Pückler połączył w niej elementy architektoniczne stworzone ręką człowieka, z elementami naturalnymi, włączając w nie geologiczne ukształtowanie terenu. Jest to charakterystyczne dla miejsca z jego niezwykłą prostotą i rozmachem przestrzennym.\n" +
            "Dobro obejmuje centralną część rozległej kompozycji krajobrazowej o powierzchni 348 ha (136,10 ha po niemieckiej stronie i 211,9 ha po polskiej). Pozostała część kompozycji znajduje się w obrębie strefy buforowej o powierzchni 1 205 ha.\n" +
            "Pückler stworzył podstawy zintegrowanego projektowania krajobrazu, gdzie park wnika w miasto Bad Muskau poprzez zielone promenady i parki miejskie. Włączenie społeczności w ogólną kompozycję, jako istotny element projektowanego utopijnego krajobrazu, miało duży wpływ na nowoczesne projektowanie miast, zwłaszcza w Stanach Zjednoczonych (co ilustruje system zieleni w Bostonie) oraz na rozwój zawodu architekta krajobrazu. Podstawy teorii projektowania krajobrazu Pücklera zostały przez niego opublikowane w „Andeutungen uber Landschaftsgartnerei” (1834). Ponadto kształcenie ogrodników krajobrazowych przez księcia Pücklera i jego ucznia Eduarda Petzolda przyczyniło się do stworzenia standardów warsztatu oddziałującego na twórczość innych ogrodników i planistów. Szkolenia te zostały współcześnie reaktywowane poprzez otworzenie „Szkoły Mużakowskiej”, międzynarodowej placówki kształcącej w dziedzinie pielęgnacji ogrodów i krajobrazu kulturowego.\n",
        ZDJECIE1: require("./images/12. Muskauer Park - Park Mużakowsk (wpis 2004)/Park Muzakowski (1).jpg"),
        ZDJECIE2: require("./images/12. Muskauer Park - Park Mużakowsk (wpis 2004)/Park Muzakowski (3).jpg"),
        ZDJECIE3: require("./images/12. Muskauer Park - Park Mużakowsk (wpis 2004)/Park Muzakowski (4).jpg"),
    }, {
        NAZWA: "XIII Hala Stulecia we Wrocławiu",
        NUMER_WPISU: "1165",
        DATA_WPISU: "2006",
        MIEJSCOWOSC: "Wrocław",
        N: 51.1085353351921,
        E: 17.0782151929286,
        OPIS: "Hala Stulecia we Wrocławiu, kamień milowy w historii architektury żelbetowej, została wzniesiona w latach 1911-1913 przez architekta Maxa Berga. Hala w rzucie ma kształt symetrycznego czteroliścia z ogromnym okrągłym pomieszczeniem centralnym, nakrytym żebrową kopułą zwieńczoną latarnią. Jej wnętrze może pomieścić do 10 000 osób.\n" +
            "Hala Stulecia to wybitny przykład wczesnego modernizmu i innowacyjnego wykorzystania konstrukcji żelbetowych w budownictwie. W momencie budowy była to największa wzniesiona dotychczas kopuła z żelbetu na świecie. Odegrała znaczącą rolę w stworzeniu nowego rozwiązania technologicznego o wysokiej wartości estetycznej, które stało się ważnym punktem odniesienia w projektowaniu przestrzeni publicznych oraz w dalszej ewolucji tej technologii. Budynek nawiązuje do form historycznych, a zarazem jest pionierskim dziełem odpowiadającym na kształtujące się potrzeby społeczne, które obejmowały funkcje takie jak: sala zgromadzeń, sala widowiskowa, przestrzeń wystawiennicza czy miejsce wydarzeń sportowych. Budowla stanowi znaczący przełom w historii współczesnej architektury.\n" +
            "Tereny Wystawowe, których głównym elementem jest zlokalizowana na przecięciu głównych osi kompozycyjnych Hala Stulecia, stanowią integralną całość przestrzenną. Zostały one zaprojektowane wspólnie przez Maxa Berga i Hansa Poelziga. Po zachodniej stronie Hali Stulecia znajduje się monumentalny plac wzorowany na starożytnym forum, poprzedzony wzniesioną w 1925 r. kolumnadą wejścia głównego. Po północnej stronie placu mieści się Pawilon Wystawy Historyczno-Artystycznej, znany pod nazwą Pawilonu Czterech Kopuł, wzniesiony w latach 1912-1913 wg projektu Hansa Poelziga. W północnej części Terenów Wystawowych znajduje się betonowa pergola otaczająca staw. Od Hali Stulecia oddziela ją budynek mieszczący restaurację z otwartym tarasem.\n" +
            "W projekcie Terenów Wystawowych połączono nowe elementy z południową częścią XIX-wiecznego Parku Szczytnickiego, wykorzystaną do prezentacji tematycznych ekspozycji ogrodowych, których przykładem jest Ogród Japoński oraz czasowej Wystawy Sztuki Cmentarnej, której pozostałością jest XVIII-wieczny drewniany kościół, przeniesiony tu z Górnego Śląska w 1912 roku.\n",
        ZDJECIE1: require("./images/13. Hala Stulecia we Wrocławiu (wpis 2006)/Wroclaw (1).jpg"),
        ZDJECIE2: require("./images/13. Hala Stulecia we Wrocławiu (wpis 2006)/Wroclaw (3).jpg"),
        ZDJECIE3: require("./images/13. Hala Stulecia we Wrocławiu (wpis 2006)/Wroclaw (4).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. Opieki Matki Bożej w Owczarach",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Owczary",
        N: 49.5886648645228,
        E: 21.1910433288353,
        OPIS: "Cerkiew parafialna z 1653 r. (obecnie kościół filialny rzymskokatolicki), trójdzielna, o konstrukcji zrębowej. Obiekt przebudowywany w XVIII i XIX w. Ściany i dachy kryte gontem, wieże i hełm kryte blachą. Portal zachodni z nadprożem wyciętym w tzw. ośli grzbiet i z wyrytą datą budowy. Nawę i sanktuarium nakrywają kopuły namiotowe. Kompletne dekoracje wnętrz z XVII-XIX w.: barokowy ikonostas, barokowe ołtarze boczne z ikonami Najświętszej Marii Panny i św. Mikołaja. Ściany pokrywają polichromie z XIX i 1. poł. XX w. Cerkiew wraz z otoczonym kamiennym ogrodzeniem dziedzińcem i ceglaną dzwonnicą jest przykładem autentycznej struktury zespołu cerkiewnego. Działania konserwatorskie w tej świątyni zostały wyróżnione międzynarodową nagrodą Europa Nostra. Doskonale zachowana cerkiew reprezentująca typ zachodniołemkowski.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Owczary/Owczary (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Owczary/Owczary (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Owczary/Owczary (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Michała Archanioła w Brunarach",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Brunary",
        N: 49.5340349552979,
        E: 21.0326194838744,
        OPIS: "Cerkiew parafialna z 1797 r. (obecnie kościół parafialny rzymskokatolicki pw. NMP Wniebowziętej) trójdzielna, o konstrukcji zrębowej. Budowla zachowała najważniejsze cechy cerkwi zachodniołemkowskiej. Dachy zwieńczone kopułami cebulastymi ze ślepymi latarniami. We wnętrzu polichromie o rokokowo klasycystycznych motywach architektonicznych oraz roślinnych z 1898 r. Zachowały się także fragmenty starszej barokowej polichromii z końca XVIII w. Barokowy ikonostas z XVIII w. przemalowany został w czasie remontu w 1831 r. W nawie trzy ołtarze boczne z 2. poł. XVIII w. − barokowy z ikoną Pieta, barokowy z ikoną Przemienienia Pańskiego, trzeci, rokokowy z ikoną Matki Boskiej z Dzieciątkiem. Zachowała się także ambona z malowanymi postaciami ewangelistów (XVIII w.) oraz ikony z XVIII i XIX w.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Brunary Wyżne/Brunary Wyzne (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Brunary Wyżne/Brunary Wyzne (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Brunary Wyżne/Brunary Wyzne (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Paraskewy w Kwiatoniu",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Kwiatoń",
        N: 49.5011846131205,
        E: 21.1739453727869,
        OPIS: "Cerkiew z XVII w. (obecnie kościół filialny rzymskokatolicki), trójdzielna, o konstrukcji zrębowej, kryta gontem. Jedna z najlepiej zachowanych klasycznych świątyń zachodniołemkowskich ze wszystkimi atrybutami. Cerkiew o wyjątkowo strzelistej bryle. Polichromia ścian i stropów o motywach architektonicznych z XVIII w. i XIX w. Dekoracje wnętrza: ikonostas pędzla Michała Bogdańskiego z 1904 r., dwa ołtarze boczne z ikonami Matki Boskiej z Dzieciątkiem oraz Zdjęcia z Krzyża, w prezbiterium XIX-wieczny ołtarz. Przykład genialnej kompozycji, najwyższego poziomu umiejętności w zakresie rzemiosła i wspaniałej zręczności stolarzy i cieśli.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Kwiatoń/Kwiaton (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Kwiatoń/Kwiaton (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Kwiatoń/Kwiaton (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Jakuba w Powroźniku",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Powroźnik",
        N: 49.3698931892239,
        E: 20.9505782355862,
        OPIS: "Cerkiew z początków XVII w., przebudowana na początku XIX w. (obecnie kościół parafialny rzymskokatolicki pw. św. Jakuba Młodszego Apostoła), trójdzielna, o konstrukcji zrębowej. W całości kryta gontem. W zakrystii zachowana została unikatowa polichromia figuralna z 1637 r. przedstawiającą sceny ze Starego i Nowego Testamentu. We wnętrzu cenne dekoracje z XVIII -XIX w.: barokowy ikonostas (XVII w.), ołtarz główny z ikoną Matki Bożej z Dzieciątkiem (XVII w.), barokowy ołtarz boczny, rokokowa ambona z 1700 r., ikony z XVII-XIX w. Jest to najstarsza cerkiew w stylu zachodniołemkowskim. Cerkiew stanowi wyjątkowy przykład translokacji drewnianego budynku. W 1813 r. ze względu na powodzie, które występowały w poprzedniej lokalizacji, konstrukcja została przeniesiona przy zachowaniu oryginalnej struktury.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Powroźnik/Powroznik (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Powroźnik/Powroznik (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Powroźnik/Powroznik (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Michała Archanioła w Smolniku",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Smolnik",
        N: 49.2096982758841,
        E: 22.6879761291679,
        OPIS: "Świątynia jest jednym z nielicznych zachowanych na terenie Polski przykładów ludowego budownictwa cerkiewnego Bojków. Zaliczana jest do typu prostego cerkwi bojkowskiej, reprezentującego najstarsze znane formy ruskich cerkwi drewnianych. Wartości obiektu zostały docenione i wyróżnione poprzez wpis na Listę światowego dziedzictwa UNESCO.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Smolnik/Smolnik (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Smolnik/Smolnik (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Smolnik/Smolnik (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. Narodzenia Przenajświętszej Bogurodzicy w Chotyńcu",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Chotyniec",
        N: 49.9529543957373,
        E: 23.0024086109302,
        OPIS: "Cerkiew jest jedną z najstarszych zachowanych świątyń drewnianych Kościoła Wschodniego w Polsce. Reprezentuje rzadko już spotykany typ cerkwi z galerią obiegającą kaplicę nad babińcem. Polichromia zachowana w nawie świątyni stanowi cenny i rzadki przykład monumentalnego malowidła ściennego zachowanego w drewnianej cerkwi. Posiada wyjątkowe walory artystyczne. Wartości obiektu zostały docenione i wyróżnione poprzez wpis na Listę światowego dziedzictwa UNESCO.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Chotyniec/Chotyniec (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Chotyniec/Chotyniec (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Chotyniec/Chotyniec (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Paraskewy w Radrużu",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Radruż",
        N: 50.1766762523025,
        E: 23.4016435469463,
        OPIS: "Cerkiew w Radrużu, z całym bogactwem swych dziejów, z monumentalną w formie architekturą i rozwiązaniami konstrukcyjnymi, należy do najcenniejszych i najstarszych cerkwi drewnianych zachowanych na terenie Polski. Obiekt jest wybitnym dziełem architektury w typie z czworoboczną kopułą nad nawą, prezentuje unikalne walory konstrukcyjne i wystrój malarski. Jej znaczenie w całokształcie najdawniejszej cerkiewnej architektury drewnianej podkreśla fakt występowania ścisłych związków warsztatowych z kilkoma zachowanymi do naszych czasów szesnastowiecznymi cerkwiami, położonymi na pograniczu polsko-ukraińskim w: Gorajcu, Potyliczu i Woli Wysockiej. Wszystkie one zostały wzniesione przez zawodowych mistrzów, wykorzystujących doświadczenia ciesielstwa późnogotyckiego. Wartości obiektu zostały docenione i wyróżnione poprzez wpis na Listę światowego dziedzictwa UNESCO.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Radruż/Radruz (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Radruż/Radruz (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Radruż/Radruz (3).jpg"),
    }, {
        NAZWA: "XIV Drewniane cerkwie polskiego i ukraińskiego regionu Karpat - Cerkiew pw. św. Michała Archanioła w Turzańsku",
        NUMER_WPISU: "1424",
        DATA_WPISU: "2013",
        MIEJSCOWOSC: "Turzańsk",
        N: 49.3691557745633,
        E: 22.1291065138486,
        OPIS: "Cerkiew wzniesiono w latach 1801-1803. W 1836 do korpusu dobudowano przedsionek i prawdopodobnie południową zakrystię. Remontowana w 1898 i 1913 r. (m. in. wymiana gontowego pokrycia dachów na blachę i powiększenie okien). Po wysiedleniu ludności ukraińskiej w 1947 r. użytkowana jako kościół rzymskokatolicki, a od 1963 r. jako cerkiew prawosławna. W l. 80., 90. XX w. oraz po 2000 r. przeprowadzono liczne remonty cerkwi.",
        ZDJECIE1: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Tutrzańsk/Tutrzansk (1).jpg"),
        ZDJECIE2: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Tutrzańsk/Tutrzansk (2).jpg"),
        ZDJECIE3: require("./images/14. Drewniane cerkwie w polskim i ukraińskim regionie Karpat (wpis 2013)/Tutrzańsk/Tutrzansk (3).jpg"),
    }, {
        NAZWA: "XV Kopalnie rud ołowiu, srebra i cynku wraz z systemem gospodarowania wodami podziemnymi w Tarnowskich Górach",
        NUMER_WPISU: "1539",
        DATA_WPISU: "2017",
        MIEJSCOWOSC: "Tarnowskie Góry",
        N: 50.4328118812197,
        E: 18.825503192594,
        OPIS: "Położone w południowej części Polski na Nizinie Śląskiej dobro, znajduje się w jednym z tradycyjnych regionów metalogenicznych - w północnej części Górnośląskiego Okręgu Przemysłowego. To największa i najważniejsza w Polsce zabytkowa kopalnia rud ołowiu, srebra i cynku wraz ze zintegrowanym systemem gospodarowania wodami podziemnymi.\n" +
            "Badania archeologiczne dowodzą, że złoża cynku i ołowiu eksploatowano na tym terenie już w III i IV wieku n.e. Pierwszy historyczny dokument potwierdzający wydobycie srebra w tej okolicy to edykt papieski z 1136 roku, wymieniający miejsce niedaleko Bytomia, na południe od Tarnowskich Gór. W 1247 roku książę opolski Władysław I wydał przywilej górniczy „plumbum habebit liberum” (zezwolenie na wydobycie ołowiu) dla dzielnicy Repty, która obecnie stanowi część Tarnowskich Gór.\n" +
            "„Ordunek Gorny” - przyjęta w 1528 roku ustawa górnicza - odzwierciedlała powstanie nowego wielonarodowego społeczeństwa górniczego, gdzie zatrudnienie znalazło wielu niemieckojęzycznych urzędników, nadzorców i górników. Wydobywany w Tarnowskich Górach ołów odegrał niezwykle istotną rolę w rozwoju europejskiego wytopu srebra w XVI w. Drugim niezwykle istotnym dla rozwoju tego miejsca okresem był XIX wiek, wówczas światowe rynki zdominował miejscowy cynk. Kopalnia i związane z nią interesy przemysłowe Państwa Pruskiego położyły podwaliny pod niemiecką rewolucję przemysłową, która rozpoczęła się właśnie na Śląsku, a wypracowany w kopalni system odwadniania pozwolił zaspokoić niemal całkowite zapotrzebowanie na wodę zarówno gwałtownie powiększającej się populacji, jak i przemysłu.\n" +
            "Trzystuletni system gospodarowania wodami podziemnymi zbudowany na płaskim i technicznie trudnym terenie niziny (różnica między najwyżej i najniżej położonym punktem terenu wynosi mniej niż 50 m) to arcydzieło inżynierii hydraulicznej. System podziemny obejmuje zlewnię wody składającą się z ponad 50 km głównych tuneli odwadniających oraz 150 km pobocznych sztolni, chodników i szybów wraz z licznymi wyrobiskami. Sieć tę uzupełniają znajdujące się zarówno pod, jak i nad ziemią pozostałości głównej infrastruktury gospodarowania wodą i bezpośrednio powiązane elementy powierzchniowe, składające się na charakterystyczny krajobraz pogórniczy. Unikatowość tego systemu gospodarowania wodami podziemnymi w skali świata, wynika z planowego i zintegrowanego także pod względem zarządczym powiązania sposobu wydobycia rud metalu z wykorzystaniem nowoczesnych wówczas maszyn parowych, z grawitacyjnym odpływem wody. W rezultacie powstał podziemny kompleks odwadniający kopalnie i jednocześnie dostarczający wodę spożywczą i przemysłową mieszkańcom Tarnowskich Gór, a przez krótki czas także całego regionu. System ten nadal funkcjonuje w dużej mierze w niezmienionej formie.\n" +
            "Większość dobra znajduje się pod ziemią, jednakże w jego skład wchodzą także obiekty na powierzchni ziemi. Bezpośrednio powiązane powierzchniowe obiekty wydobywcze to elementy sztolni, szyby oraz główna hałda usypana z odpadów powstałych w procesie przetwarzania rudy, stanowiąca żywe świadectwo rozmiarów wydobycia cynku i ołowiu w XIX w. Pozostałe niecodzienne i wyróżniające się atrybuty kulturowe obejmują park miejski – wczesny przykład udanego wykorzystania krajobrazu poprzemysłowego na cele społeczne, z dużym wyczuciem zachowujący delikatną strukturę kopców przyszybowych i hałd.\n" +
            "Charakterystyczny krajobraz pogórniczy podziwiać można na rozległym obszarze Rezerwatu Przyrody Segiet (krajobraz pogórniczy Srebrnej Góry). Widoczne są tam tzw pingi i warpie: wtórne formacje ziemne u wylotu szybu, przypominające dzwonowate wykopy charakterystyczne szczególnie dla wydobycia węgla lub otoczenia wokół kopalni krzemienia. Powstały one w rezultacie wydobycia ołowiu i srebra w XVI wieku oraz cynku i żelaza w XIX wieku.\n" +
            "Podziemne dziedzictwo pozostaje pod opieką miejscowego Stowarzyszenia Miłośników Ziemi Tarnogórskiej, którego historia sięga lat 30. XX wieku, a które działa nieprzerwanie od 1957 roku.\n",
        ZDJECIE1: require("./images/15. Kopalnia rud ołowiu, srebra i cynku wraz z systemem gospodarowania wodami podziemnymi w Tarnowskich Górach (wpis 2017)/Tarnowskie Gory (1).jpg"),
        ZDJECIE2: require("./images/15. Kopalnia rud ołowiu, srebra i cynku wraz z systemem gospodarowania wodami podziemnymi w Tarnowskich Górach (wpis 2017)/Tarnowskie Gory (2).jpg"),
        ZDJECIE3: require("./images/15. Kopalnia rud ołowiu, srebra i cynku wraz z systemem gospodarowania wodami podziemnymi w Tarnowskich Górach (wpis 2017)/Tarnowskie Gory (3).jpg"),
    },
//     {
//     NAZWA: "Kopalnie rud ołowiu, srebra i cynku wraz z systemem gospodarowania wodami podziemnymi w Tarnowskich Górach",
//     NUMER_WPISU: "1539",
//     DATA_WPISU: "2017",
//     MIEJSCOWOSC: "Tarnowskie Góry",
//     N: 50.4350097085249,
//     E: 18.8160532450956,
//     OPIS: "",
//     ZDJECIE1: require(""),
//     ZDJECIE2: require(""),
//     ZDJECIE3: require(""),
// },
];